### ISSUE TITLE
Add a new empty note

### ISSUE THREAD

**Issue by anhquangsjsu** [anhquangsjsu/team3_cs131#4]

**Comment by jasonofiana** [comment]
test test test

**Comment by jasonofiana** [comment]
I was thinking I could make a table in models.py called Notes and have it have an unique title, and a body of test as components. Also I should make it have a relationship with the User table. is this the right idea

**Comment by jasonofiana** [comment]
working on this now

**Comment by jasonofiana** [comment]
done
